### ISSUE TITLE
Wrong number of channels

### ISSUE THREAD

**Issue by danijar** [matthias-wright/jax-fid#6]
Hi, thanks a lot for this repo! I just noticed a small inconsistency. In the loaded checkpoint,  the layer `Mixed_6b/branch7x7dbl_5` has 192 channels whereas [in the code](https://github.com/matthias-wright/jax-fid/blob/fcc5bc108fc2351b06a5060932d4e9ec763f2b76/jax_fid/inception.py#L321C9-L325C74) it has `self.channels_7x7` many channels, which is 128.

I don't think it's an issue in practice, because I assume the shapes in the code don't matter when loading in external weights, but thought I'd still point it out in case it's helpful.

**Comment by matthias-wright** [comment]
Hi @danijar, thank you for pointing this out!
This should fix it https://github.com/matthias-wright/jax-fid/commit/d0d7b92697cdec5fbc23a87561da36bd072499af

**Comment by danijar** [comment]
I think the varying `self.channels_7x7` was correct, just the last layer in the 7x7 branch is always 192 channels. I wrote it [like this](https://github.com/danijar/fidjax/blob/e58d3fa027b652bacc7d18681227dd2b74d1967e/fid.py#L92C47-L92C61) in my code and the checkpoint shapes ended up matching.

**Comment by matthias-wright** [comment]
I see, thanks! I got it now https://github.com/matthias-wright/jax-fid/commit/b9a0a7e98c69b13f36fa47d661f8e16b4bbd3e83
